[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
dex = "HHtpy5cez4guhvwoXVCZzo8EUce6ouJyXaxZ7r9CVR24"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000